name: eltaff
favicon: null
layout_spectrum: 0.82561
typography_spectrum: 0.68119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#637463'
    - '#54420f'
    - '#cdc197'
    - '#fdf8db'
    - '#dba040'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
